### ISSUE TITLE
propose logo

### ISSUE THREAD

**Issue by dee-y** [intern0t/Trail#4]
Hello @intern0t  i am a graphic designer. I would like to know if you would be interested in me making a logo for this project. If you would have me, i would make a logo for you, and it's free.

**Comment by intern0t** [comment]
Sure, feel free, it's an open source project so anything is open for contribution.

Thanks for your interest.

**Comment by dee-y** [comment]
Hello @intern0t, i came up with these designs below. What do you think? 

![trail](https://user-images.githubusercontent.com/36637989/42067832-5358a90a-7b40-11e8-9f96-a86a3ea9e5e6.png)

**Comment by dee-y** [comment]
The idea behind the first 4 logos is to make the "correct mark" symbol look like a "T" for trail. The last is a ladder signifying upward movement to completion of task.

**Comment by intern0t** [comment]
I like the third one and seems to reflect this project's cause as well. Font could definitely use a bit of a touch-up with clean fonts if you don't mind me saying so. 
**But**, in overall, you did a great job!

**Comment by dee-y** [comment]
owk @intern0t, what do you think of these?...any luck?

![trail1-01](https://user-images.githubusercontent.com/36637989/42119866-06c64f06-7c09-11e8-8fb2-f2a6b01d467f.png)

**Comment by intern0t** [comment]
Definitely, the first one, do you suggest any (as a designer yourself)?

**Comment by dee-y** [comment]
After one, i would pick six because it's bold, But one definitely stands out!. lolz so are we using one?

**Comment by intern0t** [comment]
Yes, one looks pretty neat and I like the color as well, simple but goes well with this project. 




On Fri, Jun 29, 2018 at 11:06 PM -0400, "dee-y" <notifications@github.com> wrote:












After one, i would pick six because it's bold, But one definitely stands out!. lolz so are we using one?

**Comment by dee-y** [comment]
Owk great. I would have the logo files for you in a pull request soon. And
also upload all editable formats of the logo on Google drive for your
download.

Best regards,
Dee-y.

**Comment by dee-y** [comment]
Hi @intern0t, i have uploaded all versions of logo in various sizes in PNG, as well as their editable formats on google drive for your download here https://drive.google.com/drive/folders/1yqOjO8_JPDDAzE_WBpDcWmkMzhtZirLw?usp=sharing

I have also created a pull request with all sizes of logo in transparent PNG format, along with the logo license for ownership here https://github.com/intern0t/Trail/pull/5

Can't wait to see how the logo looks on your github page and on the site!

Best regards,
Dee-y.

**Comment by intern0t** [comment]
Hi @dee-y, I have integrated the logo you designed into this project and gave you the due credits. I think it looks awesome! 
You can view your name & Github profile links at the Credits section of the left navigation.

Thank you once again for your contribution! 

![Demo](https://i.imgur.com/zrkGOnD.png)

**Comment by dee-y** [comment]
:) Yess it looks wonderful and fresh...weldone!
